version: '3.9'
services:
  blog-backend:
    build: backend/
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://root:root@host.docker.internal:27017/blog?authSource=admin
    ports:
      - '3001:3001'
  blog-frontend:
    build: 
      context: .
      args:
        VITE_BACKEND_URL: http://localhost:3001/api/v1
    ports:
      - '3000:80'
    depends_on:
      - blog-backend